spring:
  config:
    import:
      - optional:classpath:secret/application-db.yml
      - optional:classpath:secret/application-cloud.yml
      - optional:classpath:secret/application-variables.yml
  application:
    name: backend
  
  profiles:
    active: ${APP_ENV:local}

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

cloud:
  aws:
    region:
      static: ${aws.region}
    s3:
      bucket: ${aws.s3.bucket}
      key: ${aws.s3.key}

app:
  jwt:
    secret: ${jwt.secret}
    expiration: ${jwt.expiration}
  cors:
    origins: ${cors.origins}
  gpu-server:
    url: ${gpu-server.url}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true


---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
