spring:
  config:
    import: "optional:classpath:secret/application-secret.yml"
  application:
    name: backend
  
  profiles:
    active: ${APP_ENV}

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_AUTH_SOURCE}
    redis:
      host: ${REDIS_HOST}
      port: 6379
  
  elasticsearch:
    uris: http://${ES_HOST}:${ES_PORT}
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION}
    s3:
      bucket: ${S3_BUCKET}

app:
  jwt:
    secret: ${SECRET_KEY}
    expiration: ${ACCESS_TOKEN_EXPIRE_MINUTES}
  cors:
    origins: ${CORS_ORIGINS}
  gpu-server:
    url: ${GPU_SERVER}
  prod-mongo:
    host: ${PROD_MONGO_HOST}
    port: ${PROD_MONGO_PORT}
    user: ${PROD_MONGO_USER}
    password: ${PROD_MONGO_PASSWORD}
    db: ${PROD_MONGO_DB}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
